### ISSUE TITLE
对于txt能不能多线路

### ISSUE THREAD

**Issue by wyx-666** [zhixc/CatVodTVSpider#1]
有时候，经常txt多个CCTV1这样的可以多线路吗，你这个项目写的很棒，不知道可不可以添加这个功能

**Comment by zhixc** [comment]
后续有空的话，我再看看这种能不能写

**Comment by wyx-666** [comment]
谢谢老哥，我自己也在想着如何写，我昨天改动了你的代码，实现了，我需要的功能，感觉就很赞

**Comment by wyx-666** [comment]
感觉我还不是很熟悉他的框架，不着急，再结合你的，我看几天应该可以进一步完善

**Comment by zhixc** [comment]
已经做了多线路

**Comment by wyx-666** [comment]
谢谢了
